const sqlite3 = require('sqlite3');
const fs = require('fs');
const path = require('path');

// A single scheduled announcement (e.g. "down Monday night for maintenance"),
// not a list — one row, always id=1, upserted in place. Separate db file from
// sessions/logins. Opened lazily (not at module load, unlike lib/loginLog.js)
// so computeStatus below stays importable/unit-testable without touching the
// filesystem — SESSION_DB_DIR only actually exists inside the container.
// `ready` is awaited by every query below before touching the connection —
// db.run(CREATE TABLE...) with no callback, immediately followed by another
// .run()/.get() on the same fresh connection, has no ordering guarantee and
// can genuinely race on a truly cold file (hit live in lib/recapUnsubscribes.js
// and lib/streamOrigins.js, which this mirrors).
let db = null;
let ready = null;
function getDb() {
  if (db) return db;
  const dbDir = process.env.SESSION_DB_DIR || '/app/data';
  fs.mkdirSync(dbDir, { recursive: true });
  db = new sqlite3.Database(path.join(dbDir, 'notice.sqlite'));
  ready = new Promise((resolve, reject) => {
    db.run(`CREATE TABLE IF NOT EXISTS notice (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      message TEXT NOT NULL,
      starts_at INTEGER,
      ends_at INTEGER,
      updated_at INTEGER
    )`, (err) => (err ? reject(err) : resolve()));
  });
  return db;
}

async function withDb() {
  const conn = getDb();
  await ready;
  return conn;
}

async function get() {
  const conn = await withDb();
  return new Promise((resolve, reject) => {
    conn.get(
      'SELECT message, starts_at AS startsAt, ends_at AS endsAt, updated_at AS updatedAt FROM notice WHERE id = 1',
      (err, row) => err ? reject(err) : resolve(row || null)
    );
  });
}

// Bind-mount destination for Kometa's config directory (see KOMETA_CONFIG_DIR
// in docker-compose.yml) — same "fixed internal path + env var gate" shape as
// MOUNT_ROOT/MEDIA_MOUNT_DIR in lib/mediaStorage.js. Left unset, the compose
// volume harmlessly re-mounts ./data and this feature just no-ops below.
const KOMETA_CONFIG_MOUNT = '/app/kometa-config';
const KOMETA_ANNOUNCEMENT_PATH = path.join(KOMETA_CONFIG_MOUNT, 'marquee-announcement.yml');

// Escapes a value for a YAML double-quoted scalar. The message is free-text
// the owner types (up to 500 chars — see routes/notice.js), so it can contain
// quotes/backslashes that would otherwise break the generated YAML.
function yamlQuote(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// Pure — testable without touching the filesystem. domain defaults to
// MARQUEE_DOMAIN the same way computeStatus below defaults now to Date.now():
// the "impure" read happens once at the call site, not buried in here.
function buildKometaYaml(message, domain = process.env.MARQUEE_DOMAIN) {
  const fullMessage = domain ? `${message} Visit ${domain} for more info.` : message;
  return `# Auto-generated by Marquee's notice board (lib/notice.js) — do not edit by
# hand, it's overwritten on every post and deleted when the notice is cleared.
collections:
  "📌 Server Announcement":
    summary: "${yamlQuote(fullMessage)}"
    plex_search:
      any:
        added.gte: 30
    limit: 1
    visible_home: true
    visible_shared: true
    visible_library: true
`;
}

// Mirrors the notice into a collection on the Plex Home screen via Kometa —
// see the "Bulletin on the Marquee" plan. Kometa only picks this up on its
// own schedule (not instant), and this deliberately doesn't account for a
// future startsAt: it mirrors whatever was just posted immediately, the same
// way the DB write above does. Non-fatal — a write failure here shouldn't
// block saving the notice itself.
function writeKometaAnnouncement(message) {
  if (!process.env.KOMETA_CONFIG_DIR) return;
  try {
    fs.mkdirSync(KOMETA_CONFIG_MOUNT, { recursive: true });
    fs.writeFileSync(KOMETA_ANNOUNCEMENT_PATH, buildKometaYaml(message), 'utf-8');
  } catch (err) {
    console.error('notice: could not write Kometa announcement mirror (non-fatal):', err.message);
  }
}

// Kometa's own config.yml always references this file's path (see the
// "Bulletin on the Marquee" plan) — deleting it outright would break Kometa's
// next scheduled run on a missing include, so clearing overwrites it with a
// valid empty collection instead of removing it.
const KOMETA_EMPTY_YAML = `# Auto-generated by Marquee's notice board (lib/notice.js) — do not edit by
# hand, it's overwritten on every post and reset here when the notice is
# cleared. Empty (no collections) means no notice is currently posted.
collections: {}
`;

function clearKometaAnnouncement() {
  if (!process.env.KOMETA_CONFIG_DIR) return;
  try {
    fs.mkdirSync(KOMETA_CONFIG_MOUNT, { recursive: true });
    fs.writeFileSync(KOMETA_ANNOUNCEMENT_PATH, KOMETA_EMPTY_YAML, 'utf-8');
  } catch (err) {
    console.error('notice: could not reset Kometa announcement mirror (non-fatal):', err.message);
  }
}

async function set({ message, startsAt, endsAt }) {
  const conn = await withDb();
  return new Promise((resolve, reject) => {
    conn.run(
      'INSERT OR REPLACE INTO notice (id, message, starts_at, ends_at, updated_at) VALUES (1, ?, ?, ?, ?)',
      [message, startsAt ?? null, endsAt ?? null, Date.now()],
      err => {
        if (err) return reject(err);
        writeKometaAnnouncement(message);
        resolve();
      }
    );
  });
}

async function clear() {
  const conn = await withDb();
  return new Promise((resolve, reject) => {
    conn.run('DELETE FROM notice WHERE id = 1', err => {
      if (err) return reject(err);
      clearKometaAnnouncement();
      resolve();
    });
  });
}

// Pure — testable without touching the DB. A missing startsAt means "show
// immediately", a missing endsAt means "show until cleared".
function computeStatus(notice, now = Date.now()) {
  if (!notice) return 'none';
  if (notice.startsAt && now < notice.startsAt) return 'scheduled';
  if (notice.endsAt && now > notice.endsAt) return 'expired';
  return 'active';
}

module.exports = { get, set, clear, computeStatus, buildKometaYaml };
